package com.example.Komorebi.models;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

import java.util.Set;

@DynamoDBTable(tableName = "Recording")
public class Recording {
    private Integer duration, video_id, note_id, customer_id;
    private Long timestamp;
    private String agent_id, category, agent_name, agent_lastname, note_text, customer_name, customer_lastname, resolution;
    private Boolean successful_outcome, allow_sharing;
    private Set<String> tag;

    // Partition key
    @DynamoDBHashKey(attributeName = "agent_id")
    @DynamoDBAutoGeneratedKey
    public String getAgent_id() { return agent_id; }
    public void setAgent_id(String agent_id) { this.agent_id = agent_id; }

    // Sort key
    @DynamoDBAttribute(attributeName = "timestamp")
    public Long getTimestamp() { return timestamp; }
    public void setTimestamp(Long timestamp) { this.timestamp = timestamp; }

    @DynamoDBAttribute(attributeName = "video_id")
    public Integer getVideo_id() { return video_id; }
    public void setVideo_id(Integer video_id) { this.video_id = video_id; }

    @DynamoDBAttribute(attributeName = "duration")
    public Integer getDuration() { return duration; }
    public void setDuration(Integer duration) { this.duration = duration; }

    @DynamoDBAttribute(attributeName = "tag")
    public Set<String> getTag() { return tag; }
    public void setTag(Set<String> tag) { this.tag = tag; }

    @DynamoDBAttribute(attributeName = "category")
    public String getCategory() { return category; }
    public void setCategory(String category) { this.category = category; }

    @DynamoDBAttribute(attributeName = "successful_outcome")
    public Boolean getSuccessful_outcome() { return successful_outcome; }
    public void setSuccessful_outcome(Boolean successful_outcome) { this.successful_outcome = successful_outcome; }

    @DynamoDBAttribute(attributeName = "agent_name")
    public String getAgent_name() { return agent_name; }
    public void setAgent_name(String agent_name) { this.agent_name = agent_name; }

    @DynamoDBAttribute(attributeName = "agent_lastname")
    public String getAgent_lastname() { return agent_lastname; }
    public void setAgent_lastname(String agent_lastname) { this.agent_lastname = agent_lastname; }

    @DynamoDBAttribute(attributeName = "note_id")
    public Integer getNote_id() { return note_id; }
    public void setNote_id(Integer note_id) { this.note_id = note_id; }

    @DynamoDBAttribute(attributeName = "note_text")
    public String getNote_text() { return note_text; }
    public void setNote_text(String note_text) { this.note_text = note_text; }

    @DynamoDBAttribute(attributeName = "customer_id")
    public Integer getCustomer_id() { return customer_id; }
    public void setCustomer_id(Integer customer_id) { this.customer_id = customer_id; }

    @DynamoDBAttribute(attributeName = "customer_name")
    public String getCustomer_name() { return customer_name; }
    public void setCustomer_name(String customer_name) { this.customer_name = customer_name; }

    @DynamoDBAttribute(attributeName = "customer_lastname")
    public String getCustomer_lastname() { return customer_lastname; }
    public void setCustomer_lastname(String customer_lastname) { this.customer_lastname = customer_lastname; }

    @DynamoDBAttribute(attributeName = "resolution")
    public String getResolution() { return resolution; }
    public void setResolution(String resolution) { this.resolution = resolution; }

    @DynamoDBAttribute(attributeName = "allow_sharing")
    public Boolean getAllow_sharing() { return allow_sharing; }
    public void setAllow_sharing(Boolean allow_sharing) { this.allow_sharing = allow_sharing; }
}
